### ISSUE TITLE
Modify the config file

### ISSUE THREAD

**Issue by dogukanteber** [cortexproject/auth-gateway#10]
Add two fields for the unauthorized server address and port to the configuration struct. It should look like this:

```
server:
  address: localhost
  port: 8080
admin:
  address: localhost
  port: 8081
tenants:
...
```
